---
- name: Create target directory
  file: path=apiserver state=directory mode=0755

- template:
    dest: apiserver/docker-compose.yml
    src: docker-compose.yml.j2
    force: yes

- command: docker-compose -f apiserver/docker-compose.yml down

- command: docker-compose -f apiserver/docker-compose.yml up -d