version: '3.7'
services:

  consul-server1:
    image: consul:1.5.1
    networks:
      istiomesh:
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    volumes:
    - ./server.hcl:/consul/config/server.hcl
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -bootstrap-expect 3 -retry-join "consul-server1" -retry-join "consul-server2" -retry-join "consul-server3"
    ports:
    - 8500:8500

  consul-server2:
    image: consul:1.5.1
    networks:
      istiomesh:
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    volumes:
    - ./server.hcl:/consul/config/server.hcl
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -bootstrap-expect 3 -retry-join "consul-server1" -retry-join "consul-server2" -retry-join "consul-server3"

  consul-server3:
    image: consul:1.5.1
    networks:
      istiomesh:
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    volumes:
    - ./server.hcl:/consul/config/server.hcl
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -bootstrap-expect 3 -retry-join "consul-server1" -retry-join "consul-server2" -retry-join "consul-server3"

  etcd:
    image: quay.io/coreos/etcd:latest
    networks:
      istiomesh:
    command: ["/usr/local/bin/etcd", "-advertise-client-urls=http://0.0.0.0:2379", "-listen-client-urls=http://0.0.0.0:2379"]

  istio-apiserver:
    image: k8s.gcr.io/kube-apiserver-amd64:v1.10.11
    networks:
      istiomesh:
        aliases:
          - apiserver
    ports:
      - "8080:8080"
    privileged: true
    command: ["kube-apiserver", "--etcd-servers", "http://etcd:2379", "--service-cluster-ip-range", "10.99.0.0/16", "--insecure-port", "8080", "-v", "2", "--insecure-bind-address", "0.0.0.0"]


networks:
  istiomesh:
    name: consul_istiomesh
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16