apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: details
  namespace: default
spec:
  workloadSelector:
    labels:
      app: details
  egress:
  - hosts:
    - "istio-system/*"